# Generated by Django 5.1.2 on 2024-11-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swag', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
