# Generated by Django 5.1.2 on 2024-11-19 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swag', '0002_remove_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
